"""description

Revision ID: 411b9947af59
Revises: 8c42616dd087
Create Date: 2026-01-31 08:18:35.909547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411b9947af59'
down_revision = '8c42616dd087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_paiement', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('fullname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('operator', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depot', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('operator')
        batch_op.drop_column('fullname')
        batch_op.drop_column('phone_paiement')

    # ### end Alembic commands ###
