"""Initialisation après création forcée

Revision ID: 6da2799d0189
Revises: 
Create Date: 2026-03-18 10:32:21.630556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da2799d0189'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_vendeur', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'produit', ['produit_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['vendeur_id'], ['id'])

    with op.batch_alter_table('paiement', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'produit', ['produit_id'], ['id'])

    with op.batch_alter_table('verification_request', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('paiement', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('message_vendeur', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
